language: python
sudo: required
services:
  - docker
python:
  - 3.5

install:
  - pip install -e .
  - pip install pytest-xdist

script:
  # Run at least 4 tests in parallel. These tests are all fully
  # parallelizable
  - pytest -v -n4 tests/${REPO_TYPE}

env:
  - REPO_TYPE=conda
  - REPO_TYPE=venv
  - REPO_TYPE=julia
