# py3.5 conda packages are no longer being updated as of 12/2018
# this file is hand-maintained now
# and should only receive security fixes, no new features
name: r2d
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - backcall=0.1.0=py_0
  - bleach=3.0.2=py_0
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.10.15=ha4d7672_0
  - certifi=2018.8.24=py35_1001
  - decorator=4.3.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.2.3=py35_2
  - gmp=6.1.2=hfc679d8_0
  - ipykernel=5.1.0=pyh24bf2e0_0
  - ipython=7.0.1=py35h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.2.1=py35_1
  - jedi=0.12.1=py35_0
  - jinja2=2.10=py_1
  - jsonschema=2.6.0=py35_2
  - jupyter_client=5.2.3=py_1
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.34.9=py35_0
  - jupyterlab_launcher=0.13.1=py_2
  - libffi=3.2.1=hfc679d8_5
  - libgcc-ng=7.2.0=hdf63c60_3
  - libsodium=1.0.16=h470a237_1
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - markupsafe=1.0=py35h470a237_1
  - mistune=0.8.3=py35h470a237_2
  - nbconvert=5.4.0=1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hfc679d8_1
  - openssl=1.0.2p=h470a237_1
  - pandoc=1.19.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.5=py35_0
  - pip=18.0=py35_1001
  - prometheus_client=0.4.2=py_0
  - prompt_toolkit=2.0.7=py_0
  - ptyprocess=0.6.0=py35_1000
  - pygments=2.2.0=py_1
  - python=3.5.5=h5001a0f_2
  - python-dateutil=2.7.5=py_0
  - pyzmq=17.1.2=py35hae99301_0
  - readline=7.0=haf1bffa_1
  - send2trash=1.5.0=py_0
  - setuptools=40.4.3=py35_0
  - simplegeneric=0.8.1=py_1
  - six=1.11.0=py35_1
  - sqlite=3.25.3=hb1c47c0_0
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35_1
  - tk=8.6.9=ha92aebf_0
  - tornado=5.1.1=py35h470a237_0
  - traitlets=4.3.2=py35_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.32.0=py35_1000
  - widgetsnbextension=3.2.1=py35_1
  - xz=5.2.4=h470a237_1
  - zeromq=4.2.5=hfc679d8_6
  - zlib=1.2.11=h470a237_3
  - pip:
    - alembic==1.0.3
    - async-generator==1.10
    - chardet==3.0.4
    - idna==2.7
    - jupyterhub==0.9.4
    - mako==1.0.7
    - notebook==5.7.8
    - nteract-on-jupyter==1.9.6
    - pamela==0.3.0
    - python-editor==1.0.3
    - python-oauth2==1.1.0
    - requests==2.20.1
    - sqlalchemy==1.2.14
    - urllib3==1.24.1
prefix: /opt/conda/envs/r2d
